<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.xvn</groupId>
		<artifactId>xvn-parent</artifactId>
		<version>1.0-SNAPSHOT</version>
	</parent>

	<artifactId>xvn-book-network</artifactId>
	<version>1.0-SNAPSHOT</version>
	<description>Xvn Book Social Network Backend</description>

	<properties>
		<java.version>21</java.version>
		<org.mapstruct.version>1.5.5.Final</org.mapstruct.version>
		<org.projectlombok.version>1.18.30</org.projectlombok.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
			<version>${org.mapstruct.version}</version>
		</dependency>
		<!-- xvn dependencies -->
		<dependency>
			<groupId>com.xvn</groupId>
			<artifactId>xvn-common-core</artifactId>
		</dependency>
		<dependency>
			<groupId>com.xvn</groupId>
			<artifactId>xvn-common-feign</artifactId>
		</dependency>
		<dependency>
			<groupId>com.xvn</groupId>
			<artifactId>xvn-common-log</artifactId>
		</dependency>
		<dependency>
			<groupId>com.xvn</groupId>
			<artifactId>xvn-common-multi-db</artifactId>
		</dependency>
		<dependency>
			<groupId>com.xvn</groupId>
			<artifactId>xvn-common-redis</artifactId>
		</dependency>
		<dependency>
			<groupId>com.xvn</groupId>
			<artifactId>xvn-common-sec</artifactId>
			<version>1.0-SNAPSHOT</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>${org.mapstruct.version}</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${org.projectlombok.version}</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok-mapstruct-binding</artifactId>
							<version>0.2.0</version>
						</path>
						<path>
							<groupId>org.hibernate.orm</groupId>
							<artifactId>hibernate-jpamodelgen</artifactId>
							<version>${jpa.modelgen.version}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
