spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: postgres
    password: Gx@YJ0505
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    consumer:
      group-id: xvn-book-network-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.xvn.*
  mail:
    host: localhost
    port: 1025
    username: xvn
    password: xvn
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    org.postgresql: INFO

application:
  security:
    jwt:
      secret-key: 4f4e6e7c4f5b7df8e3a6c5a4e9b2f4a7f9e6c4b3d7a8a4c8f9e2b4f5d3c7e8a5
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      photos-output-path: ./uploads