spring:
    profiles:
        active: dev
    application:
        name: book-network-backend
    servlet:
        multipart:
            max-file-size: 50MB
    data:
        rest:
            default-media-type: application/json

server:
    servlet:
        context-path: /api/v1


skip-filter-url: >
    /public/**,
    /v2/api-docs,
    /v3/api-docs,
    /v3/api-docs/**,
    /swagger-resources,
    /swagger-resources/**,
    /configuration/ui,
    /configuration/security,
    /swagger-ui/**,
    /webjars/**,
    /swagger-ui.html

