spring:
    profiles:
        active: dev
    application:
        name: book-network-backend
    servlet:
        multipart:
            max-file-size: 50MB
    data:
        rest:
            default-media-type: application/json
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.add.type.headers: true
        consumer:
            group-id: xvn-book-network-consumer
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: com.xvn.*

server:
    servlet:
        context-path: /api/v1


skip-filter-url: >
    /public/**,
    /v2/api-docs,
    /v3/api-docs,
    /v3/api-docs/**,
    /swagger-resources,
    /swagger-resources/**,
    /configuration/ui,
    /configuration/security,
    /swagger-ui/**,
    /webjars/**,
    /swagger-ui.html
