spring:
  datasource:
    url: jdbc:postgresql://localhost:54322/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: xvn
    password: xvn
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 4f4e6e7c4f5b7df8e3a6c5a4e9b2f4a7f9e6c4b3d7a8a4c8f9e2b4f5d3c7e8a5
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account